// src/components/SocialMediaScreen.js

import React, { useState, useEffect } from "react";
import axios from "axios";

const BACKEND_URL = "http://localhost:5000";

// Dynamically generates a prompt for any mood
function generatePromptForMood(mood) {
  if (!mood || typeof mood !== "string" || mood.trim() === "") {
    mood = "neutral";
  }
  return `“A stylized photo instagram post (without the UI) designed to support the mood ‘${mood}’:

– If negative (anxious, sad, angry, overwhelmed): show a peaceful scene like gentle ocean waves, soft pastel colors, and a minimal layout with a calm tone.
– If neutral: show an uplifting article preview or news snippet with balanced composition, soft lighting, and a hint of curiosity or inspiration (like a sunrise or a glowing headline).
– If positive: display a cheerful, vibrant post celebrating joy—bright colors, confetti, smiling icons, or a celebration scene.

Requirements:
• Clean layout, subtle shadows, realistic or semi-realistic visual style.
 `;
}

function SocialMediaScreen({ mood }) {
  const [images, setImages] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // For debugging: see what mood is coming in
  useEffect(() => {
    console.log("Received mood from backend:", mood);
  }, [mood]);

  useEffect(() => {
    async function fetchImages() {
      setLoading(true);
      setError(null);
      setImages([]);
      const prompt = generatePromptForMood(mood);
      try {
        const response = await axios.post(`${BACKEND_URL}/api/generate-image`, {
          prompt,
        });
        setImages(response.data.images || []);
      } catch (e) {
        setImages([]);
        setError(
          e.response && e.response.data && e.response.data.error
            ? e.response.data.error
            : "Image generation failed."
        );
      }
      setLoading(false);
    }
    fetchImages();
  }, [mood]);

  return (
    <div style={{ maxWidth: 700, margin: "50px auto", textAlign: "center" }}>
      <div
        style={{
          marginBottom: 32,
          padding: "18px 30px",
          background: "#f3f7ff",
          borderRadius: 12,
          border: "1px solid #dbeafe",
          fontSize: 20,
          color: "#183153",
          textAlign: "center",
          boxShadow: "0 2px 8px #0001",
        }}
      >
        <span style={{ fontWeight: 500, fontSize: 22, color: "#375bb6" }}>
          Mood detected:&nbsp;
        </span>
        <span style={{ fontWeight: 700, fontSize: 22, textTransform: "capitalize" }}>
          {mood || "neutral"}
        </span>
        <div style={{ marginTop: 12, fontSize: 17 }}>
          The feed below is generated by AI to visually reflect your mood.
        </div>
      </div>
      <h2>Social Mood Feed</h2>
      {error && (
        <div style={{ color: "red", margin: 16 }}>{error}</div>
      )}
      {loading ? (
        <p>Generating images...</p>
      ) : (
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            flexWrap: "wrap",
            gap: 20,
          }}
        >
          {images.length > 0 ? (
            images.map((img, idx) => (
              <div
                key={idx}
                style={{
                  border: "1px solid #ddd",
                  borderRadius: 10,
                  padding: 10,
                }}
              >
                <img
                  src={img}
                  alt={`mood img ${idx}`}
                  style={{
                    width: 200,
                    height: 200,
                    objectFit: "cover",
                    borderRadius: 10,
                  }}
                />
              </div>
            ))
          ) : (
            <div style={{ color: "#666" }}>No images generated.</div>
          )}
        </div>
      )}
    </div>
  );
}

export default SocialMediaScreen;