// src/components/SocialMediaScreen.js

import React, { useState, useEffect } from "react";
import { useMood } from "../contexts/MoodContext";
import api from "../api";
import styles from "./SocialMediaScreen.module.css";

function generatePromptForMood(mood) {
  if (!mood || typeof mood !== "string" || mood.trim() === "") {
    mood = "neutral";
  }
  return `A stylized photo designed to support the mood '${mood}'. 
  
  GENERATE EITHER ONE OF THE FOLLOWING OPTIONS:
– If negative (sad, frustrated, anxious, angry): show a peaceful scene like gentle ocean waves, soft pastel colors, and a minimal layout with a calm tone.
– If neutral: A lived-in room lit by morning light, the space holding a quiet sense of ${mood}
– If positive: A joyful backyard dinner party at dusk, long wooden table under string lights, friends of diverse backgrounds laughing and talking, reflecting a ${mood} atmosphere.

Requirements:
• Clean layout, subtle shadows, semi-realistic visual style.`;
}

function SocialMediaScreen() {
  // 1) Read `mood` from context instead of via props
  const { mood } = useMood();

  const [imageUrl, setImageUrl] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    console.log("Received mood from context:", mood);
  }, [mood]);

  useEffect(() => {
    async function fetchImage() {
      setLoading(true);
      setError(null);
      setImageUrl(null);

      const prompt = generatePromptForMood(mood);
      try {
        const url = await api.generateImage(prompt);
        setImageUrl(url || null);
      } catch (e) {
        setImageUrl(null);
        setError(e.response?.data?.error || "Image generation failed.");
      }

      setLoading(false);
    }
    fetchImage();
  }, [mood]);

  return (
    <div className={styles.feedContainer}>
      <h2 className={styles.feedTitle}>Your Mock-up Feed</h2>

      <div className={styles.moodInfoBox}>
        <span className={styles.moodLabel}>Mood detected:&nbsp;</span>
        <span className={styles.moodValue}>{mood || "neutral"}</span>
        <div className={styles.moodDescription}>
          The feed below is generated by AI to balance your current mood.
        </div>
      </div>

      {error && <div className={styles.error}>{error}</div>}

      {loading ? (
        <p className={styles.loading}>Generating image...</p>
      ) : imageUrl ? (
        <div className={styles.imageCard}>
          <div className={styles.imageHeader}>
            <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
              <img
                src="/chatbot-avatar.png"
                alt="avatar"
                className={styles.avatarSmall}
              />
              <span className={styles.username}>AI_Generator</span>
            </div>
            <span className={styles.imageHeaderRight}>⋯</span>
          </div>
          <img src={imageUrl} alt={`mood img`} className={styles.image} />
          <div className={styles.reactions}>
            <span>❤️</span>
            <span>💬</span>
            <span>📤</span>
          </div>
          <div className={styles.caption}>
            <strong>AI_Generator</strong>
            This post was created to gently shift you into a better headspace.
            <div className={styles.captionTag}>#{mood}vibes</div>
          </div>
          <div className={styles.timestamp}>2 HOURS AGO</div>
        </div>
      ) : (
        <div className={styles.noImages}>No image generated.</div>
      )}
    </div>
  );
}

export default SocialMediaScreen;